# アクセシビリティチェック
accessibility:
  # michecer
  severity:
    ignore: 0
    error: 1
    warning: 2
    user: 4
    info: 8

  # チェック対象となるHTML要素
  target:
    id: 'page-content'
    css: 'div#page-content'
    xpath: '//div[@id="page-content"]'

  # ブロック要素の制限
  block:
    limit:
      warning:
        text: 1000

      error:
        text: 3000
        header: 35

  # altの文字数制限
  alt:
    minimum: 3
    maximum: 149

  # style属性の制限
  style:
    font_size:
      # フォントサイズに指定できない単位
      disabled_units:
        - pt
        - px
        - ex

  # リンクの制限
  link:
    external_label: '外部サイト'
    not_uploadable_types:
      - audio
      - video

  # 下記のエラーIDをsusanoo用のエラー種別に変換する
  policy:
    ignore:
      - B_12
      - B_17
      - B_22
      - B_23
      - B_24
      - B_33
      - B_35
      - L_1.2
      - L_3
      - C_14.0
      - C_18.0
      - C_18.1
      - C_18.2
      - C_20.0
      - C_42.0
      - C_43.0
      - C_68.0
      - C_70.0
      - C_71.0
      - B_1
      - B_2
      - B_4
      - B_5
      - B_6
      - B_10
      - B_16
      - B_21
      - B_25
      - B_27
      - B_30
      - B_31
      - B_36
      - B_37
      - B_38
      - C_1000.0
      - C_1000.1
      - C_1000.2
      - C_1000.3
      - C_1000.4
      - C_1000.5
      - C_1000.6
      - C_1000.7
      - L_1.0
      - L_1.1
      - L_2
      - L_4
      - L_5
      - L_6
      - C_0.0
      - C_0.1
      - C_0.2
      - C_1.1
      - C_2.0
      - C_2.1
      - C_2.2
      - C_3.0
      - C_4.0
      - C_5.4
      - C_7.0
      - C_9.0
      - C_10.0
      - C_12.2
      - C_21.0
      - C_27.0
      - C_27.1
      - C_28.0
      - C_29.0
      - C_29.1
      - C_29.2
      - C_30.0
      - C_30.1
      - C_31.0
      - C_33.0
      - C_33.1
      - C_33.2
      - C_34.0
      - C_36.0
      - C_36.1
      - C_38.0
      - C_39.0
      - C_40.0
      - C_41.0
      - C_45.0
      - C_45.1
      - C_47.0
      - C_48.0
      - C_48.1
      - C_48.2
      - C_48.3
      - C_48.4
      - C_48.5
      - C_49.0
      - C_50.0
      - C_51.0
      - C_51.1
      - C_51.2
      - C_51.3
      - C_51.4
      - C_51.5
      - C_52.0
      - C_52.1
      - C_53.1
      - C_54.0
      - C_54.1
      - C_55.0
      - C_57.0
      - C_57.3
      - C_57.4
      - C_59.1
      - C_59.2
      - C_59.3
      - C_60.0
      - C_60.1
      - C_61.0
      - C_62.0
      - C_63.0
      - C_66.0
      - C_67.0
      - C_68.1
      - C_69.0
      - C_73.0
      - C_74.0
      - C_74.1
      - C_74.2
      - C_77.0
      - C_77.1
      - C_77.2
      - C_79.0
      - C_79.1
      - C_79.2
      - C_79.3
      - C_79.4
      - C_79.5
      - C_79.6
      - C_79.7
      - C_78.2
      - C_81.0
      - C_82.0
      - C_84.0
      - C_85.0
      - C_86.0
      - C_87.0
      - C_88.0
      - C_90.0
      - C_90.1
      - C_200.0
      - C_200.1
      - C_201.0
      - C_201.1
      - M_1
      - C_3.1
      - C_6.1
      - C_21.1
      - C_21.2
      - C_53.2
      - C_54.2
      - C_54.3
      - C_54.4
      - C_320.0
      - C_321.0
      - C_322.0
      - C_380.0
      - C_381.0
      - C_382.0
      - C_383.0
      - C_384.0
      - C_385.0
      - C_386.0
      - C_387.0
      - C_388.0
      - C_389.0
      - C_421.0
      - C_421.1
      - C_500.3
      - C_500.5
      - C_500.6
      - C_500.7
      - C_500.8
      - C_500.9
      - C_500.10
      - C_500.12
      - C_500.13
      - C_500.14
      - C_500.15
      - C_500.16
      - C_500.17
      - C_500.18
      - C_500.19
      - C_500.20
      - C_300.1
      - C_300.2
      - C_300.3
      - C_600.1
      - C_600.2
      - C_600.3
      - C_600.4
      - C_600.5
      - C_600.6
      - C_600.7
      - C_600.8
      - C_600.9
      - C_600.10
      - C_600.11
      - C_600.13
      - C_600.15
      - C_600.16
      - C_600.17
      - C_600.18

    error:
      - B_15
      - B_29
      - C_46.0
      - C_48.6
      - C_57.2
      - C_76.0
      - C_80.0
      - C_500.0
      - C_500.1

  # アクセシビリティチェックで始めの見出しレベルで許可する対象の設定
  accessibility_h_level:
    - 1
    - 2
